"use client";

import { Activity, ArrowUpRight, CircleAlert, Database, LoaderCircle, RefreshCw, Server, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";

type Status = { hindsight: { configured: boolean; connected: boolean }; llm: { configured: boolean }; bankId: string; lastMemorySync: string | null };

export default function SettingsPage() {
  const [status, setStatus] = useState<Status | null>(null);
  const [checking, setChecking] = useState(false);
  const [seeding, setSeeding] = useState(false);
  const [seedMessage, setSeedMessage] = useState("");
  async function refresh() { setChecking(true); try { const response = await fetch("/api/status", { cache: "no-store" }); setStatus(await response.json()); } catch { setStatus({ hindsight: { configured: false, connected: false }, llm: { configured: false }, bankId: "unavailable", lastMemorySync: null }); } finally { setChecking(false); } }
  useEffect(() => {
    let active = true;
    fetch("/api/status", { cache: "no-store" }).then((response) => response.json()).then((data) => { if (active) setStatus(data); }).catch(() => { if (active) setStatus({ hindsight: { configured: false, connected: false }, llm: { configured: false }, bankId: "unavailable", lastMemorySync: null }); });
    return () => { active = false; };
  }, []);
  async function seedDemo() { setSeeding(true); setSeedMessage("Checking Hindsight for existing demo records..."); try { const response = await fetch("/api/memory/seed", { method: "POST" }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setSeedMessage(result.added ? `${result.added} demo records retained; ${result.existing} already existed.` : "Demo records already exist in this bank. No duplicates created."); } catch (error) { setSeedMessage(error instanceof Error ? error.message : "Demo seed failed."); } finally { setSeeding(false); } }
  return <>
    <div className="page-heading"><div><div className="eyebrow">CONFIGURATION <span>·</span> SERVICE HEALTH</div><h1>System status</h1><p>Integration connectivity is verified server-side. Secret values are never sent to this page.</p></div><button className="button" onClick={() => void refresh()} disabled={checking}>{checking ? <LoaderCircle className="spin" size={14} /> : <RefreshCw size={14} />} Refresh status</button></div>
    <div className="status-summary panel"><div className="status-summary-icon"><Activity size={18} /></div><div><strong>{!status ? "Checking integrations..." : status.hindsight.connected ? "Memory service connected" : "Running in demo mode"}</strong><p>{!status ? "Contacting configured services." : status.hindsight.connected ? "A live Hindsight version check succeeded from the server." : "Historical examples are synthetic demo data; no Hindsight retrieval is occurring."}</p></div><span className={`summary-status ${status?.hindsight.connected ? "summary-online" : ""}`}><i />{status?.hindsight.connected ? "OPERATIONAL" : "NOT CONNECTED"}</span></div>
    <div className="integration-grid">
      <IntegrationCard icon={Database} title="Hindsight" subtitle="Persistent long-term memory" connected={Boolean(status?.hindsight.connected)} configured={Boolean(status?.hindsight.configured)} description={status?.hindsight.connected ? "Version endpoint responded. Incident memory retain and recall use the configured bank." : "Set the Hindsight URL and bank ID in the server environment, then restart the app."} />
      <IntegrationCard icon={Sparkles} title="Groq" subtitle="Incident analysis model" connected={false} configured={Boolean(status?.llm.configured)} statusLabel={status?.llm.configured ? "CONFIGURED · NOT PROBED" : "NOT CONFIGURED"} bottomLabel={status?.llm.configured ? "Key present · service not probed" : "Rule-based fallback active"} description={status?.llm.configured ? "An API key is configured, but connectivity is verified only when incident analysis runs. Rule-based analysis remains available." : "No API key detected. Rule-based analysis uses retrieved memory and safe generic fallbacks."} />
    </div>
    <section className="panel connection-details"><div className="panel-title">Connection details</div><div className="connection-row"><span>Hindsight base URL</span><strong>{status?.hindsight.configured ? "Configured · hidden" : "Not configured"}</strong></div><div className="connection-row"><span>Memory bank ID</span><strong className="mono">{status?.bankId || "Checking..."}</strong></div><div className="connection-row"><span>Hindsight API key</span><strong>{status?.hindsight.configured ? "Server-side · not exposed" : "Not configured"}</strong></div><div className="connection-row"><span>Groq API key</span><strong>{status?.llm.configured ? "Server-side · not exposed" : "Not configured"}</strong></div><div className="connection-row"><span>Last memory sync</span><strong>{status?.lastMemorySync || "No sync recorded"}</strong></div></section>
    <section className="panel setup-panel"><span className="setup-icon"><Server size={15} /></span><div className="setup-copy"><div className="panel-title">Configure integrations</div><p>Copy <code>.env.example</code> to <code>.env.local</code> and add values on the server. Restart Next.js after changing environment variables.</p><pre>HINDSIGHT_API_KEY=...<br />HINDSIGHT_BASE_URL=https://your-hindsight-host<br />HINDSIGHT_BANK_ID=incidentiq<br />GROQ_API_KEY=...</pre></div><span className="setup-security"><ShieldCheck size={13} /> SERVER-ONLY SECRETS</span></section>
    <section className="panel seed-settings"><div><Database size={15} /><span><strong>Load synthetic demo memories</strong><small>Checks for existing demo records before retaining the synthetic incident examples.</small></span></div><button className="button button-small" disabled={!status?.hindsight.connected || seeding} onClick={() => void seedDemo()}>{seeding ? <><LoaderCircle className="spin" size={12} /> Seeding...</> : status?.hindsight.connected ? "Load demo memories" : "Requires Hindsight"}</button></section>{seedMessage && <div className="seed-message">{seedMessage}</div>}
    <div className="security-footnote"><CircleAlert size={13} /> No credentials are hardcoded. Hindsight and Groq keys remain in server environment variables; the browser receives status only.</div>
  </>;
}

function IntegrationCard({ icon: Icon, title, subtitle, connected, configured, description, statusLabel, bottomLabel }: { icon: typeof Database; title: string; subtitle: string; connected: boolean; configured: boolean; description: string; statusLabel?: string; bottomLabel?: string }) { return <section className="panel integration-card"><div className="integration-top"><span className="integration-icon"><Icon size={16} /></span><span className={`integration-pill ${connected ? "connected-pill" : ""}`}><i />{statusLabel || (connected ? "CONNECTED" : configured ? "UNREACHABLE" : "NOT CONFIGURED")}</span></div><h2>{title}</h2><div className="integration-subtitle">{subtitle}</div><p>{description}</p><div className="integration-bottom"><span><i className={connected ? "online" : ""} />{bottomLabel || (connected ? "Health verified" : "Fallback available")}</span><ArrowUpRight size={13} /></div></section>; }